tooling/lint.sh

Until I find a better solution, to work around XCode not coming with `clang-tidy` support, I wrote a quick bash script you can run to get the same result.
Run `./lint.sh` inside the `tooling` folder. It worked on Demi's old Macbook.
The only file I added.
Hopefully this is temporary.

Script for Mac Users to Run clang-tidy

---

build-apple/Sweetspace.xcodeproj/project.pbxproj

See title.
Added all files under `source/` to xcode project and deleted HelloApp.*
Build succeeds.

Added code files to xcode project and cleaned up useless ones.

---

source/InputController.cpp

Copied in a `LISTENER_KEY` macro
Builds on Windows, at least
Made a CI pipeline that tries to compile the iOS version of the app, and it seems to pass as well (see status checks section below).
It's a one line fix.

Add LISTENER_KEY Constant

---

source/InputController.cpp

Quick change to Accelerometer X Factor based on testing; this can be adjusted later as we see fit
Movement seems to be not too fast, not too slow based on this constant
N/A

Accelerometer

---

source/InputController.cpp
source/InputController.h

Mouse Callbacks implemented
Printed to output when click up occurs
InputController

Mouse support

---

build-android/app/build.gradle
build-android/build.gradle
source/InputController.cpp

Added some friction when rolling on desktop so that the ship slows and stops properly.
App builds and runs both on my computer and my phone.
See `InputController`
At some point we're going to want to rewrite the physics code because it's pretty bad right now.

Rolling friction

---

source/InputController.cpp

Remove an empty if statement
Game builds
N/A

Cleanup Empty If

---

source/BreachModel.cpp
source/BreachModel.h
source/DonutModel.cpp
source/DonutModel.h
source/GMController.cpp
source/GameGraphRoot.cpp
source/GameGraphRoot.h
source/GameMode.cpp
source/InputController.cpp

Jumping Added on click/tap. Breaches now need to be rolled over a few times to be resolved. 
Runs smoothly on my laptop.
Testing on mobile device and changing variables for max jump height and gravity for a better feeling jump. The variables are JUMP_HEIGHT and GRAVITY in DonutModel.cpp. The breach health can be changed via the health option in the Breach constructor in Breach.h

Jumping donuts

---

build-apple/Sweetspace.xcodeproj/project.pbxproj
cugl/build-apple/Box2D.xcodeproj/project.pbxproj
cugl/build-apple/Box2D.xcodeproj/xcuserdata/onewordstudios.xcuserdatad/xcschemes/xcschememanagement.plist
cugl/build-apple/CUGL.xcodeproj/project.pbxproj
cugl/lib/audio/graph/CUAudioOutput.cpp

Properly configured XCode team and deployment certificates and added in audio bug fix from Piazza
Still compiles on my machine.
Manual deployment to TestFlight worked.
As long as it compiles. It's all boilerplate stuff.

Audio Bug Fix + XCode Team Setup

---

build-win10/Sweetspace/Sweetspace.vcxproj
build-win10/Sweetspace/Sweetspace.vcxproj.filters
source/MagicInternetBox.cpp
source/MagicInternetBox.h

Create the basic interface for the networking controller class, so that I'm hopefully no longer blocking anyone else from working.
No implementation in this PR; just adds an interface.
Game still compiles, since nothing was actually changed.
The header file has methods and documentation.
First, there's no way to broadcast to other players that a breach has lost health. I don't think this is a dealbreaker for technical prototype; we can just have the breach disappear on another player's screen for now, since they're probably not paying a ton of attention to breaches that aren't theirs. This can be changed later.
Second, the `update()` method will need to take in the `ShipModel` object to actually do things like easing the position of other donuts and stuff each frame, and creating the new …

Setup Networking Interface

---

build-apple/Sweetspace.xcodeproj/project.pbxproj
source/ShipModel.h

Added getters/setters for shipmodel.h
Builds
See if there's any other things ship model should have getters/setters for

Ship Model Header File Added

---

build-apple/Sweetspace.xcodeproj/project.pbxproj
build-win10/Sweetspace/Sweetspace.vcxproj
build-win10/Sweetspace/Sweetspace.vcxproj.filters
source/BreachModel.cpp
source/BreachModel.h
source/GMController.cpp
source/GMController.h
source/GameMode.cpp
source/GameMode.h
source/ShipModel.cpp
source/ShipModel.h

Added ShipModel.cpp, updated ShipModel.h and BreachModel to reflect the changes in ShipModel
Builds
Take a look at createBreach & resolveBreach

added shipmodel.cpp

---

source/MagicInternetBox.cpp

Azure's seemingly undocumented limit of 5 concurrent connections for their free plan was too annoying to deal with. Eventually, I think we should move towards an Ad-Hoc server. For now, I spun up a free-tier Heroku Dyno. In my super fast testing, I got at least 7 clients connected to it simultaneously, which is definitely more than 5, so let's just run with this for now.
Still compiles on Windows.
It's a one-line change.
I haven't set up CI auto-deployment for the Heroku dynamo yet, so committing to the server repo will _not_ autodeploy at the moment. I'll try to set that up later.

Change Server to Heroku

---

README.md
build-android/app/.gitignore
build-android/app/build.gradle
build-apple/Resources/iOS-Info.plist
build-apple/Sweetspace.xcodeproj/project.pbxproj
cugl/build-apple/Box2D.xcodeproj/xcuserdata/onewordstudios.xcuserdatad/xcschemes/xcschememanagement.plist

Added a README for technical prototype, as well as made Android and iOS builds.
Didn't change code. Both Google Play Internal Testing and TestFlight builds work properly.
The `README` changes.

Technical Prototype Release

---

source/.clang-tidy
source/MagicInternetBox.cpp
source/MagicInternetBox.h
source/MatchmakingMode.cpp
source/MatchmakingMode.h

Rework `mib` to better support the matchmaking process.
Now `mib` has an `update()` method that takes no parameters which can be called during the matchmaking phase. In addition, it has a `matchStatus()` method that can be called to query the status of the matchmaking, including if any errors have occurred and the specific details if so.
Tested across three Windows instances, and runs fine.
The changes in `mib` and the `MatchmakingMode`.

Refactor Matchmaking

---

source/MagicInternetBox.cpp
source/MagicInternetBox.h

Create basic support in the header of `mib` for restoration of game.
Close #74 
Still compiles. No functionality was implemented or changed at this time.
`mib`

Create Basic Restoration Support in MIB header

---

build-android/app/src/main/AndroidManifest.xml
build-apple/Resources/iOS-Info.plist
build-apple/Sweetspace.xcodeproj/project.pbxproj

Modify project configs so that:
1. The app will not deploy to any device that doesn't support the required OpenGL ES 3 that CUGL uses
2. The app will not deploy to mobile devices without accelerometers
3. The iOS Simulator version builds correctly again.
Built on Windows, macOS, iOS, and iOS Simulator.
Frankly nothing. It's all config changes.

Declare build features

---

assets/json/assets.json
build-apple/Sweetspace.xcodeproj/project.pbxproj
source/MatchmakingGraphRoot.cpp
source/MatchmakingGraphRoot.h

Changes
- Moved textfield for entering room id to top
- Made default text "sweet"
- Repositioned elements
- Added header file for matchmaking SGR to xcode proj
Tested with mac and ios builds.

Non cancerous textbox

---

source/DonutNode.cpp
source/GameMode.cpp
source/MagicInternetBox.cpp
source/MagicInternetBox.h

Networked jumping works now.
Close #58 
Tested across three Windows instances.
Works correctly.
All of it.

Networked Jump

---

source/GameMode.cpp

Simple collision between donuts and breaches that aren't yours. Jumping into a breach that isn't yours vibrates you until you jump out.
Tested on multiple instances.
Gamemode changes.

Collision no box2d

---

source/BreachModel.h
source/ExternalDonutModel.cpp
source/GameMode.cpp
source/MagicInternetBox.cpp
source/MagicInternetBox.h

Periodically (every second) synchronize the state of all the doors and breaches against the definitive state provided by the host.
Close #46 
Tested on Windows by manually disabling synchronization of breach creation, breach resolution, and door creation. After 1 second, state sync worked as expected.
All interesting changes are in `mib`

State Synchronization

---

source/GameMode.cpp

Hotfix a botched merge conflict resolution
Works on Windows with 3 players.
N/A

Fix Breach Fixing

---

source/GLaDOS.cpp

Prevent breaches from spawning on top of each other.
Does not prevent breaches from spawning on doors.
Tested on Windows w/ 3 players. Seems to work.
Only one file was changed.

Stop Breaches Spawning On Top of Each Other

---

README.md

Pre-Alpha README

---

README.md
build-android/app/build.gradle
build-apple/Resources/Mac-Info.plist
build-apple/Sweetspace.xcodeproj/project.pbxproj
cugl/build-apple/Box2D.xcodeproj/xcuserdata/onewordstudios.xcuserdatad/xcschemes/xcschememanagement.plist

Bump all respective version numbers for pre-alpha release
No code was changed. Still builds on all platforms.

Pre Alpha Version Bump

---

source/HealthNode.cpp

Health bar display adjusted from scenegraph refactor
Builds and displays as it should
Make sure it displays

Health bar display update

---

build-apple/Sweetspace.xcodeproj/project.pbxproj

See title
Tested on Mac build. Music plays in game.

Add music folder to xcode project

---

cugl/lib/base/platform/CUDisplay-iOS.mm

See Piazza @96: https://piazza.com/class/k5oahf584os660?cid=96
Game still compiles and runs no problem.
N/A

CUGL Hotfix: Fix iOS Safe Area

---

tooling/lint.sh

Update the bash script to let macOS users run `clang-tidy` on their code.
Fix #105 
To use the script, go into the tooling folder in your terminal.
In AppCode, the terminal should be one of the built-in tabs along the bottom, and should default to the project root, so you should be able to `cd tooling` (or maybe `cd ../tooling` if you start inside `build-apple`) fairly easily.
From there, run the `lint.sh` script, passing it the name of the `cpp` file you want to lint (without the extension).
For example, to check the Ship Model, I'd run
./lint.sh ShipModel
And the script will print out any warnings and / or errors.
Note you can tab-autocomplete the `./lint.sh` part (but not the class name, sadly).
You can also run the linter on the entire codebase by passing it the word `all`, like so …

macOS Linting Script

---

source/.clang-tidy
source/BreachModel.cpp
source/BreachModel.h
source/BreachNode.cpp
source/DonutNode.cpp
source/DoorModel.h
source/DoorNode.cpp
source/GLaDOS.cpp
source/GLaDOS.h
source/GameMode.cpp
source/LoadingMode.cpp
source/MagicInternetBox.cpp
source/MatchmakingGraphRoot.cpp
source/MatchmakingGraphRoot.h
source/ShipModel.cpp
source/ShipModel.h

Fix linter warnings in all classes except `GameGraphRoot`, which I'm leaving for @wenjiazhang, and `HealthNode`, which I'd like some help from @asaxena5 from b/c the warnings are kind of overwhelming. 
Partially addresses #104 
Runs fine on Windows
It's basically all just small tweaks and fixes to make the linter happy.

Fix (some) Linter Warnings

---

source/DonutModel.cpp
source/DonutModel.h
source/ExternalDonutModel.cpp
source/ExternalDonutModel.h
source/GLaDOS.cpp
source/GLaDOS.h
source/GameGraphRoot.cpp
source/GameMode.cpp
source/PlayerDonutModel.cpp
source/PlayerDonutModel.h
source/ShipModel.cpp
source/ShipModel.h

Refactoring PR. Because levels can be larger than 360 degrees, we need to be able to scale the size of a level. To all models, the level is simply a linear line that wraps around at the end, which means the level size/max degrees can be >=360. Added `maxDegree` field to multiple model-related classes with source coming from GameMode to accommodate future level files.
- `GameMode` initializes `ship` and `gm` with level size
- Added field and changed constructors for `ShipModel`
- Added field and changed constructors for `DonutModel` and children
- Added field and changed constructors for `GLaDOS`
- Made minor changes in drawing in `GMRoot`
**NOTE:** This refactor does not mean that the max level can be changed to whatever you want because the drawing code is still not updated to …

Variable level size

---

build-apple/Sweetspace.xcodeproj/project.pbxproj
build-win10/Sweetspace/Sweetspace.vcxproj
build-win10/Sweetspace/Sweetspace.vcxproj.filters
source/BreachNode.cpp
source/DonutNode.cpp
source/DoorNode.cpp
source/ExternalDonutModel.cpp
source/GameGraphRoot.cpp
source/GameMode.cpp
source/Globals.h
source/HealthNode.cpp
source/LoadingMode.cpp
source/MagicInternetBox.cpp
source/MatchmakingGraphRoot.cpp
source/MatchmakingMode.cpp
source/ShipModel.cpp
source/main.cpp

Refactor out common constants into a namespace called `globals` in a separate `Globals.h` file.
The intent is to not have all the constants in the game in this one file, but rather only the constants that are of general interest to multiple classes (so individual pixel offsets can stay inside their respective node classes, for example).
Should be merged **after** #107 
Close #99
Game still builds on Windows
Take a look at which constants I pulled out into `Globals.h` and let me know if there are any other constants that you believe also deserve to be put in there.

Refactor Constants

---

source/DoorModel.h
source/GameMode.cpp
source/GameMode.h
source/InputController.cpp
source/InputController.h
source/LoadingMode.cpp
source/LoadingMode.h
source/MagicInternetBox.h
source/MatchmakingMode.h
source/Sweetspace.cpp
source/Sweetspace.h

Removed all traces of `Ship Demo` (that I could find) from comments and documentation.
Didn't change code
Just make sure everything still looks legit, I guess.

Cleanup Documentation References

---

cugl/build-apple/Box2D.xcodeproj/xcuserdata/aashnasaxena.xcuserdatad/xcschemes/xcschememanagement.plist
source/HealthNode.cpp
source/MatchmakingMode.cpp

Resolved the errors given in HealthNode
Runs as normal.
N/A

Health node clang-tidy fixes

---

source/GLaDOS.cpp
source/GLaDOS.h
source/GameMode.cpp
source/GameMode.h
source/MagicInternetBox.cpp
source/MagicInternetBox.h
source/MatchmakingMode.cpp
source/MatchmakingMode.h
source/Sweetspace.cpp
source/Sweetspace.h

Make `mib` a real singleton.
Runs fine on Windows
`mib`, primarily.

Network singleton

---

build-apple/Resources/iOS-Info.plist
cugl/build-apple/Box2D.xcodeproj/xcuserdata/onewordstudios.xcuserdatad/xcschemes/xcschememanagement.plist

Happy now, @Jeffrey-J-Yao ?
Close #101
Tested on Demi's old iPhone.
N/A

Allow iOS Rotations

---

assets/json/level.json

Change the min angle between donuts doors and breaches.
It works now. It's only one line. Trust me.

change min angle

---

README.md
build-android/app/build.gradle
build-android/build.gradle
build-apple/Sweetspace.xcodeproj/project.pbxproj
cugl/build-apple/Box2D.xcodeproj/xcuserdata/onewordstudios.xcuserdatad/xcschemes/xcschememanagement.plist

Bump version numbers and add README for Alpha.
No code changes.
N/A

Alpha Release

---

source/GameMode.cpp
source/GameMode.h
source/InputController.cpp
source/InputController.h
source/MatchmakingMode.cpp
source/MatchmakingMode.h
source/Sweetspace.cpp

Refactor InputController to be a singleton class.
Also cleaned up unused variables, refactored the detection of how jumps happen (spacebar also triggers jump now, like a tRuE gAmEr), and moved the initialization and disposal around.
Since the class is now a singleton and is accessed exclusively by reference, there's no real reason to separate out the construction from initialization, and vice-versa with destruction and disposal, so they happen together now.
Close #131
Game still runs on Windows
Changes to `InputController`, primarily.
I'll probably refactor `ButtonManager` next, since `InputController` is now a singleton.

Refactor Input Controller

---

source/ButtonManager.cpp
source/ButtonManager.h
source/MatchmakingGraphRoot.cpp
source/MatchmakingGraphRoot.h
source/MatchmakingMode.cpp

Refactor the `ButtonManager` class to properly work with the new singleton Input Controller.
More refactoring in the future needs to be done, w.r.t. #149 , but it's fine for now. 
Still runs on Windows
`ButtonManager` and the `Matchmaking` classes

Refactor Button Manager

---

source/BreachNode.cpp

Just a quick one-line fix to breach drawing logic.

Set isShown to false when breachNode finishes last animation

---

assets/json/assets.json
source/GameGraphRoot.cpp

Re-anchored the `field` node to top center of screen and repositioned all children to match change
Close #150 
Tested on Mac and iOS builds

Re-anchored field node and repositioned all children

---

assets/json/level.json
source/GameGraphRoot.cpp
source/GameGraphRoot.h

- Ship sections are now labeled with a number in counterclockwise direction. For now labels are only numbers, once we have multiple colored ship assets we could implement letters and numbers.
- Changed level size to multiple of 45.
Close #145 
Tested on Mac and iOS builds.

Label ship sections

---

source/GameMode.cpp

Tweak the slowdown constants so you don't lose as much speed on your own breach, and collision detection with other breaches is more generous.
Runs fine on Windows. If you get a chance, pull and play around to see how these feel.
The constants

Tweak Breach Slowdown Constants

---

source/MagicInternetBox.cpp

Health and timer status now sync along with doors and breaches.
Close #137 
Important to note; this is supposed to be to fix desyncs, not to transmit critical game data. The fact that health wasn't syncing across all devices originally means there's a failure somewhere else in the code to properly compute health on clients (since clients have access to the full state of the ship; it's not the host's job to broadcast ship health). That still needs to be fixed, independent of this PR.
`mib`

Sync State

---

build-android/app/build.gradle
build-apple/Sweetspace.xcodeproj/project.pbxproj
cugl/build-apple/Box2D.xcodeproj/xcuserdata/onewordstudios.xcuserdatad/xcschemes/xcschememanagement.plist

Bump version numbers for the pre-beta in-class release.

Pre-Beta Presentation Version Number Bump

---

source/MainMenuMode.cpp

Fix regression from #181 where clients entering incorrect room ID would hang forever.
Close #195 
Works on Windows
Changes in Main Menu Mode.

Fix Invalid Client ID Update

---

source/GameMode.cpp
source/MagicInternetBox.cpp
source/MagicInternetBox.h
source/ShipModel.cpp
source/ShipModel.h

Make it so that the status of breaches getting fixed syncs across the network, instead of just when the breach is resolved.
Close #127
Tested on Windows. Works.
Changes in `mib` are all cleanup related. Primary changes are in `GameMode` and `ShipModel`, as well as documentation changes in `mib` and `ShipModel`.

Sync Breach Fix Status

---

README.md
build-android/app/build.gradle
build-apple/Sweetspace.xcodeproj/project.pbxproj
cugl/build-apple/Box2D.xcodeproj/xcuserdata/onewordstudios.xcuserdatad/xcschemes/xcschememanagement.plist

Pre-Beta Release Version Number Bump + README

---

build-win10/Sweetspace/Sweetspace.vcxproj.filters
source/.clang-tidy
source/BreachNode.cpp
source/ButtonModel.cpp
source/ButtonNode.cpp
source/GLaDOS.cpp
source/GLaDOS.h
source/GameGraphRoot.cpp
source/GameMode.cpp
source/Globals.h
source/HealthNode.cpp
source/MagicInternetBox.cpp
tooling/lint.sh

Clean up all linter warnings in our current code, and set up a CI job to enforce the linter's static analysis checks on all our code going forward.
Is currently **NOT** a blocking check, as it takes almost 8 minutes to run. We can change this in the future if necessary.
Seems to run fine on my branch.
Linter fixes in the code (mainly pulling out magic numbers).

Linter Enforcement

---

source/Globals.h
source/ShipModel.h

Fix a magic number in `ShipModel.h`. I forgot that our automated CI check doesn't check header files.
Game still compiles.

Fix Magic Number in Ship Model

---

source/ButtonModel.cpp
source/ButtonModel.h
source/ButtonNode.cpp
source/GLaDOS.cpp
source/GameGraphRoot.cpp
source/GameMode.cpp
source/Globals.h
source/MagicInternetBox.cpp
source/MagicInternetBox.h
source/ShipModel.cpp
source/ShipModel.h

Change button model to require simultaneously jumping on the button to resolve.
Button resolution has been changed so that while all players still handle button flagging, only the second player to jump on a button is responsible for resolving the button task. This player is authoritative over that resolution process, broadcasting its result to other players. This mitigates a potential de-sync due to jumps being potentially multiple frames different between different clients.
Close #216 
Works on Windows
Changes to `ButtonModel` and `ShipModel` are noteworthy.

Simultaneous Button Jump

---

assets/json/assets.json
build-android/build.gradle
source/GameGraphRoot.cpp

Fix the win screen, loss screen, reconnecting screen, and pause screen scene graphs.
Works on Windows (even after changing the aspect ratio) and my Android-running Pixel 3XL, which did not work earlier today in class.
Scene graph changes, sadly.

Fix Overlay Scene Graph

---

source/ExternalDonutNode.cpp
source/Globals.h
source/PlayerDonutNode.cpp

Adjust the speed donuts spin when they roll to make things look microscopically better
Tested on windows

slightly change spin speed

---

README.md
build-android/app/build.gradle
build-apple/Sweetspace.xcodeproj/project.pbxproj

Bump version numbers and update README

Beta Release

---

source/GameMode.cpp

Hot fix for crashing upon level transition when someone left during the level.
Tested on Windows.
GameMode

Fix Level Transition Crash

---

source/GameGraphRoot.cpp
source/GameMode.cpp
source/LevelConstants.h
source/MainMenuMode.cpp
source/Sweetspace.cpp

Level files are now stored into an indexable array instead of as individual constants, making getting levels easier.
Tested on Windows
@ssorenson130 Please check changes to `LevelConstants.h`
@asaxena5 Please check changes to the tutorial; I had to change your code to be zero-indexed.

Refactor Level Files

---

build-android/app/build.gradle
build-android/app/src/main/res/values/styles.xml
build-apple/Resources/Mac-Info.plist
build-apple/Resources/iOS-Info.plist
build-apple/Sweetspace.xcodeproj/project.pbxproj

Hack to workaround the fact that CUGL doesn't draw around Android notches correctly.
Tested on Pixel 3 XL.
N/A
Technically this is wrong because we need to target SDK min 27 in order to use the notch styles, but changing the min SDK from 21 to 27 causes the game to crash because of something with SDL. Walker is advising us to compile SDL from source, but I'm lazy and this seems to work as long as we run on new enough Android devices.

Fix Android Notch

---

.github/CODEOWNERS
source/DonutNode.cpp
source/GLaDOS.cpp
source/GameGraphRoot.cpp
source/GameMode.cpp
source/TutorialNode.cpp
tooling/lint.sh

Fix the CI script for the linter, and also clean up stray linter warnings.
Also created a `CODEOWNERS` file that will hopefully automatically tag people to review changes to files they've contributed heavily too. We'll see if that works.
I encourage y'all to edit the `CODEOWNERS` file as you create new files in the future or shift responsibilities around.
Runs on Windows still; no functionality changes implemented.
Mainly, see whether the `CODEOWNERS` file makes sense.

Fix Linter Warnings + Set Up Codeowners

---

.editorconfig
.gitignore
assets/json/assets.json
source/GameGraphRoot.cpp
source/GameGraphRoot.h

Disable the restart and next buttons at the end of a level for everyone except the host.
Prevents race conditions where multiple people tap the button together.
Also removed the poorly named and confusing "levels" button that actually booted people out of the game.
Everything except the `.editorconfig` file; that's just to make GitHub show tabs correctly.

Disable next

---

source/GLaDOS.cpp
source/GameMode.cpp
source/MainMenuMode.cpp
source/ShipModel.h
source/Sweetspace.cpp
source/TutorialConstants.h

Fix linter warnings

---

cugl/lib/2d/physics/CUPolygonObstacle.cpp
cugl/lib/assets/CUTextureLoader.cpp
cugl/lib/base/CUApplication.cpp

From Walker on Piazza.
https://piazza.com/class/k5oahf584os660?cid=143
Seems like our memory usage went down a bit to 700MB now.
Tested on Windows.
N/A

Fix CUGL Memory Leaks

---

source/GLaDOS.cpp
source/GameGraphRoot.cpp
source/MainMenuMode.cpp

Fix invisible join button for clients, and disable invisible next level / restart buttons for clients.
Also fixed a stray crash and tweaked the level select transition a tiny bit.
Tested on Windows
All of it.

Fix Buttons

---

source/GameGraphRoot.cpp

fixed health bar so it resets after every level

health bar fix

---

source/GameMode.cpp
source/SoundEffectController.h

resets the sound each level, in case someone ends a level on a door
tested for two players

reset sound each level

---

assets/json/assets.json

Updated position of timer border so that it is no longer hardcoded. It doesn't float in the middle of the screen on the iPad anymore!
Tested on Mac and iPad (screenshot is on iPad)

(Tiny change) Timer border position fix

---

source/MainMenuMode.cpp

Hide start button before min number of players have joined.
Close #288
Tested returning to main menu after game; still works.
All of it.

Hide Start

---

source/GameMode.cpp

Fixed the jittering that happened when you ran up against a door, which involved moving where the donut model updates were handled to a more logical place in the frame.
Also removed self slowdown; it feels a little weird to me now; tbh idk if I like it.
Close #298
Ran on Windows fine.
Honestly, playtest yourself and see if it feels weird to fix your own breaches without any noticeable slowdown. It feels weird to me, but that's likely just because I'm too used to the old way.

Fix Door Jitter & Remove Self Slowdown

---

source/CustomNode.cpp
source/CustomNode.h

Add two additional lifecycle methods to `CustomNode`, called on state transitions of the return value of `isActive`.

Additional Lifecycle Methods

---

build-android/app/build.gradle
build-apple/Sweetspace.xcodeproj/project.pbxproj

Bump version number for intermediate rollout to test door fixes

Version Number Bump

---

source/GameGraphRoot.cpp
source/GameGraphRoot.h

- Switched appearance order to space out pink and purple

Space apart pink and purple to avoid confusion

---

source/GameGraphRoot.cpp

Cleanup sparkle nodes and player donut node on level dispose.
Works on Windows; checked static CustomNode set of all instantiated custom nodes. Correctly resets to 0 on level transition.

Fix Memory Leak

---

source/MagicInternetBox.cpp

fix active players

---

source/ButtonNode.cpp

Fix Button Tutorial

---

assets/json/assets.json
source/MainMenuMode.cpp
source/MainMenuMode.h

Display the number of joined players once a player joins a game.
Close #333
Both the design, and if you want, please compile and make sure that I didn't break anything on subsequent plays (ex: joining a game, quitting, and then joining another game still works, but I may have missed some specific sequence of actions).

Better Join Feedback

---

.github/CODEOWNERS
build-win10/Sweetspace/Sweetspace.vcxproj
build-win10/Sweetspace/Sweetspace.vcxproj.filters
source/GLaDOS.cpp
source/GameGraphRoot.cpp
source/GameMode.cpp
source/MagicInternetBox.cpp
source/MagicInternetBox.h
source/MainMenuMode.h
source/ShipModel.cpp
source/ShipModel.h
source/StabilizerModel.cpp
source/StabilizerModel.h

Pulled all the stabilizer stuff out of `ShipModel` and into `StabilizerModel` instead.
Also rewrote the stabilizer to require 60 frames of rolling in the same direction (not necessarily continuous) instead of prior behavior which required only 10 frames but didn't despawn the dialog box until 120 frames, for some weird reason.
Close #286
`StabilizerModel` is stored directly by `ShipModel` instead of as a pointer since there will only ever be a single stabilizer at any time. The stabilizer is returned as a reference by `getStabilizer()` instead of a smart pointer for that reason.
Works across Windows and Mac (I added the appropriate files to the XCode project too).
`StabilizerModel` is the focus. As with all these stacked PRs, this changelog won't be very helpful until the prior PRs are …

Stabilizer

---

source/GameMode.cpp
source/GameMode.h

Just a quick little refactor.
Moved all the discrete chunks of `GameMode`'s update method into their own helper methods, so that the actual `update` flow of `GameMode` is much easier to read (and thus easier to reorder if needed for logic reasons).
Works on Windows.
`GameMode`

Cleanup GameMode

---

cugl/lib/base/CUDisplay.cpp

See title. Fix is for iPhone XR and 11 Pro Max
Close #341 
Demi tested on an XR

Fix accelerometer orientation

---

.github/CODEOWNERS
build-apple/Sweetspace.xcodeproj/project.pbxproj
build-win10/Sweetspace/Sweetspace.vcxproj
build-win10/Sweetspace/Sweetspace.vcxproj.filters
source/MagicInternetBox.cpp
source/MagicInternetBox.h
source/StateReconciler.cpp
source/StateReconciler.h

Reworked state sync from the ground up.
Now syncs not only breaches and doors, but buttons as well.
In addition, instead of immediately correcting discrepancies, any detected anomalies are buffered until the next state sync, and only corrected if still present then. This should fix the problem with breaches flickering in and out of existence if resolved by a client too close to a state sync.
Close #349
Worked on Windows and Mac.
Moved state sync code into its own class, called `StateReconciler`. 
Most of the work was done there.

Redone State Sync

---

source/GLaDOS.cpp
source/GLaDOS.h
source/GameMode.cpp
source/GameMode.h
source/MagicInternetBox.cpp
source/MagicInternetBox.h
source/MainMenuMode.cpp
source/ShipModel.cpp

Make the clients check whether their API versions are compatible with each other before allowing the connection to continue.
Should be merged in conjunction with PR number 3 on the server side.
**May break backwards compatibility with old builds.**
Close #347 
Also did a ton of testing and debugging for why we're getting out-of-bounds button IDs, and can't find the issue, so I'm removing the check for now in the hopes that if it does ever surface, we'll get a crash report.
Close #264
Runs on Windows.
`mib` I guess

API Updates

---

assets/json/assets.json
source/MainMenuMode.cpp
source/MainMenuMode.h

Added new error screen for client join failures. 
If @demidimi can get me a new button asset that says "retry", I can change the error screen to have a button instead of just saying tap anywhere.
Close #350
The new designs, and please make sure it doesn't break anything else, such as the ability to host a game after failing to join as a client or whatever.

Better Client Join Error Screens

---

build-android/app/build.gradle
build-apple/Sweetspace.xcodeproj/project.pbxproj

Bump version number for new TestFlight and Google Play release.

API Version Bump

---

source/MainMenuMode.cpp

Fixes the first half of #357 
Works on Windows, fixing both the invisible back button and escape key presses.
N/A

Prevent Host from Backing Out after Players Join 

---

source/GLaDOS.cpp
source/ShipModel.cpp
source/ShipModel.h

Should fix the event generation bug where events "run out" if people take too long on buttons
Close #334 
tested with @mt-xing

fix event generation

---

source/MainMenuMode.cpp
source/MainMenuMode.h

Animate the needle on the host screen that shows the number of players.
N/A

Animate Host Player Count Needle

---

source/GameGraphRoot.cpp

Fix #351 
Tested on Windows
All

Fix Stabilizer Fail Ghost Objects

---

assets/json/assets.json
build-android/app/jni/Application.mk
build-apple/Sweetspace.xcodeproj/project.pbxproj
build-win10/Sweetspace/Sweetspace.vcxproj
build-win10/Sweetspace/Sweetspace.vcxproj.filters
source/AnimationManager.cpp
source/AnimationManager.h
source/MagicInternetBox.cpp
source/MainMenuMode.cpp
source/MainMenuMode.h
source/MainMenuTransitions.cpp
source/MainMenuTransitions.h
source/Tween.h

Makes no changes in functionality.
Pulls all animations from `MainMenuMode` out into a helper class to clean up the main class.
Also cleaned up the XCode project to sort the files just like the Visual Studio project did, instead of just having a huge barf of files in the top level `source` folder.
Seriously, Mac users. Damn, y'all lived like this?
Finally, had to bump the C++ version on Mac, iOS, and Android to C++14 to enable `make_unique`, as C++ 11 didn't have that. The Windows project was already on C++14.
Played around. Still works.
Honestly, it's all just UI garbage.

Main Menu Transitions Refactor

---

assets/json/assets.json
source/ButtonNode.cpp
source/ButtonNode.h
source/GameGraphRoot.cpp
source/GameGraphRoot.h

Reused sparkle effect for button resolve animation. Close #371 
Tested on Mac build

Button disappear animation

---

source/Globals.h
source/MagicInternetBox.cpp
source/NetworkConnection.cpp

Have the client check the API version on connection.
Close #377
Pretty small change; should be easy to review once the ad-hoc server itself is merged.
Host does not yet check API version with the punchthrough server.
Also currently it takes a few seconds for the host to realize that the connection failed, but it does work itself out eventually.

API Versioning

---

build-android/.idea/codeStyles/Project.xml
build-android/.idea/misc.xml
build-android/app/build.gradle
build-android/build.gradle
build-apple/Sweetspace.xcodeproj/project.pbxproj

Release the ad-hoc server to our testing channels. Mainly allows us to take down the old Heroku relay server.

Ad-Hoc Release

---

build-win10/Sweetspace/Sweetspace.vcxproj
cugl/include/cugl/assets/CUAssetManager.h
source/GameGraphRoot.cpp
source/InputController.cpp
source/MagicInternetBox.cpp
source/MainMenuMode.cpp
source/MainMenuMode.h
source/MainMenuTransitions.cpp
source/MainMenuTransitions.h
source/SoundEffectController.cpp
source/Sweetspace.cpp

Fixed the transition to the credits after beating the last level.
Close #380
Ran on Windows and it worked
Mainly main menu stuff

Fix Credits Transition

---

source/MagicInternetBox.cpp
source/NetworkConnection.h

Fixed a particularly nasty networking bug where entering an invalid room ID would cause a crash, but only sometimes.
Works on Windows now.
All of it. It's short.

Fix Networking Crash

---

tooling/lint.sh

Change the CI pipeline to only lint changed `.cpp` files for pull requests, hopefully speeding up the wait time.

Speedup CI Lint

---

source/MagicInternetBox.cpp
source/MagicInternetBox.h
source/MainMenuMode.cpp
source/MainMenuTransitions.cpp
source/NetworkConnection.cpp

Display intelligent error messages on connection failures, such as no internet or API level mismatches.
Close #383
Tested on Windows; host errors are a bit uglier than client errors but it no longer just crashes, which is the important part, I guess.
Once #388 and #391 are merged, this should be a fairly small PR.

Better Connection Errors

---

tooling/lint.sh

One More CI Hotfix

---

assets/json/assets.json
build-apple/Sweetspace.xcodeproj/project.pbxproj
build-win10/Sweetspace/Sweetspace.vcxproj
build-win10/Sweetspace/Sweetspace.vcxproj.filters
source/GameGraphRoot.cpp
source/GameGraphRoot.h
source/Tween.cpp
source/Tween.h
source/WinScreen.cpp
source/WinScreen.h

Merge after #397
Add some animation to the victory screen, showing the same map from level select and an animated dot that travels representing the player's current progress.
Part of #387
It's quite ugly right now; still waiting on designer input before this screen is finalized, but with the code written, swapping out the design should be fairly trivial.
https://user-images.githubusercontent.com/6147405/104830024-31b88d00-5848-11eb-9f70-3bff679cfd0c.mp4
Runs on Windows
Focus on the new `WinScreen` class.

Level Win Screen Improvements

---

assets/json/assets.json
build-apple/Sweetspace.xcodeproj/project.pbxproj
build-win10/Sweetspace/Sweetspace.vcxproj
build-win10/Sweetspace/Sweetspace.vcxproj.filters
cugl/build-apple/Box2D.xcodeproj/xcuserdata/mt_xing.xcuserdatad/xcschemes/xcschememanagement.plist
source/AudioController.h
source/ButtonManager.cpp
source/ButtonManager.h
source/GameGraphRoot.cpp
source/GameGraphRoot.h
source/GameMode.cpp
source/MainMenuMode.cpp
source/MainMenuMode.h
source/MainMenuTransitions.cpp
source/NeedleAnimator.h
source/PauseMenu.cpp
source/PauseMenu.h
source/Tween.cpp
source/Tween.h

Redid the pause menu, pulling it out into its own class.
The menu is now also animated, as is the needle inside the menu showing the number of players.
All other functionality should still work as well.
https://user-images.githubusercontent.com/6147405/104958426-047df300-599e-11eb-81ef-0b77bc818816.mp4
Tested on Windows and iOS.
Most interesting changes are in `PauseMenu`. However, the `AudioController` and `NeedleAnimator` classes are also new, consisting of refactored code I pulled out from the pause menu.

Pause Menu Refactor

---

assets/json/assets.json
build-win10/Sweetspace/Sweetspace.vcxproj
build-win10/Sweetspace/Sweetspace.vcxproj.filters
source/ButtonNode.cpp
source/ButtonNode.h
source/DoorNode.cpp
source/DoorNode.h
source/ExternalDonutNode.cpp
source/ExternalDonutNode.h
source/GameGraphRoot.cpp
source/GameGraphRoot.h
source/Globals.h
source/PlayerDonutNode.cpp
source/PlayerDonutNode.h
source/ShipSegmentNode.cpp
source/ShipSegmentNode.h
source/ShipSegmentWrap.cpp
source/ShipSegmentWrap.h

Cleanup game graph root a bit by moving ship segments into their own node class and also cleaning up some other stray small things.
**This probably won't compile because I batched adding new files to XCode in the next PR. This should be merged together with #401**
Tested on Windows
Predominately the new ship segment classes, and the changes to `GameGraphRoot`.

Game Graph Root Basic Cleanup

---

assets/json/assets.json
build-apple/Sweetspace.xcodeproj/project.pbxproj
build-win10/Sweetspace/Sweetspace.vcxproj
build-win10/Sweetspace/Sweetspace.vcxproj.filters
source/GameGraphRoot.cpp
source/GameGraphRoot.h
source/GameMode.cpp
source/MagicInternetBox.cpp
source/ReconnectScreen.cpp
source/ReconnectScreen.h
source/ShipModel.cpp
source/WinScreen.cpp
source/WinScreen.h

Continuing the refactor of `GameGraphRoot` by pulling the reconnecting screen into its own class.
Allows it to be animated.
Didn't bother changing the color of the donut to match the player because without the eyes the donut looks weird anyways and I presume we're gonna redesign this screen at some point.
https://user-images.githubusercontent.com/6147405/105896408-be034680-5fe4-11eb-9da3-2aaef595fd05.mp4
Tested on Windows.
The new reconnection screen class

Reconnect Screen Rewrite

---

source/MainMenuTransitions.cpp
source/NetworkConnection.cpp

There was an issue where the game would crash while attempting to reconnect if you performed any actions since it was trying to send to a null network connection. Should be fixed now.
On an unrelated note, made a **very** minor tweak to the opening animation of the game to parallax the logo in a bit. Thought it looked nicer that way.
Networking tested with multiple instances on Windows.
Here's what the new title screen animation looks like:
https://user-images.githubusercontent.com/6147405/106335344-9fa68080-625a-11eb-8631-9b72eb505550.mp4
Trivial

Hotfix Networking Crash

---

assets/json/assets.json

Modified scaling and position of health bar assets to fix its curvature. Only confirmed on Windows 10. Close #405
Screenshot from Windows 10 debugger
If possible check that it looks right on other devices, but probably shouldn't be an issue.

Health bar position fix

---

source/.clang-tidy
source/GLaDOS.cpp
source/MainMenuMode.cpp
source/MainMenuMode.h
source/ShipModel.h
source/Tween.cpp
source/main.cpp

The CI seems to have updated to LLVM 12, so I updated myself and also fixed any warnings I could find.
Runs on Windows
All

Fix Clang-Tidy Warnings

---

source/GameMode.cpp
source/MagicInternetBox.cpp

I _think_ I fixed the host networking issue?
Close #414
I tried starting a game with two players and disconnecting the client; the host no longer warns of an uncaught value, which it used to.
Not sure if this fully fixes the problem, but it's what I was able to recreate.
See if you still get the same error.

Fix reconnect failed room ID

---

source/NetworkConnection.cpp

Google Cloud updated their free tier and I had to restart the server and get a new IP as a result.

Fix Server IP

---

build-win10/Sweetspace/Sweetspace.vcxproj
cugl/build-win10/Box2D/Box2D.vcxproj
cugl/build-win10/CUGL/CUGL.vcxproj

Retarget to VS 2022. No changes needed. Hot reload is crazy cool.
Compiles on Windows. Compatible with prior builds.
N/A

Retarget Windows Project to VS 2022
